export const data = [
  { Company: "JSW", EmpCode: "7045087", Name: "Rajesh K" },
  { Company: "JSW", EmpCode: "7042000", Name: "Shashidhar Patil" },
  { Company: "JSW", EmpCode: "1101744", Name: "Abhishek Marwadi" },
  { Company: "JSW", EmpCode: "7045723", Name: "Prashanth" },
  { Company: "JSW", EmpCode: "7045599", Name: "Ganga K T" },
  { Company: "JSW", EmpCode: "1049303", Name: "Indi Omkareshwar" },
  { Company: "JSW", EmpCode: "1046499", Name: "Panchadarla Srinu" },
  { Company: "JSW", EmpCode: "1046850", Name: "Vijay Durgesh K G" },
  { Company: "JSW", EmpCode: "1101421", Name: "Vighnesh Mhatre" },
  { Company: "JSW", EmpCode: "1098394", Name: "Ranganath" },
  { Company: "JSW", EmpCode: "1096588", Name: "Dinesh Panwar" },
  { Company: "JSW", EmpCode: "1089219", Name: "Abhimanyu Sharma" },
  { Company: "JSW", EmpCode: "1049295", Name: "Honnuraswamy K" },
  { Company: "JSW", EmpCode: "1023097", Name: "Swamy L M" },
  { Company: "JSW", EmpCode: "1022784", Name: "Karthik A R" },
  { Company: "JSW", EmpCode: "1018443", Name: "Subhansab Mattihalli" },
  { Company: "TTPS", EmpCode: "CSLV079826", Name: "Amrender Tiwari" },
  { Company: "TTPS", EmpCode: "CSLV007219", Name: "Mukesh Prajapati" },
  { Company: "TTPS", EmpCode: "CSLV099777", Name: "Parasurama HP" },
  { Company: "TTPS", EmpCode: "CSLV098624", Name: "Fayazahmad Nadaf" },
  { Company: "TTPS", EmpCode: "CSLV086507", Name: "Dangi Hemantharaj" },
  { Company: "TTPS", EmpCode: "CSLV076425", Name: "G M Thippeswamy" },
  { Company: "TTPS", EmpCode: "CSLV063576", Name: "P Rakesh Kumar" },
  { Company: "TTPS", EmpCode: "CSLV056474", Name: "Maruthi" },
  { Company: "TTPS", EmpCode: "CSLV016636", Name: "Manjunatha N" },
  { Company: "TTPS", EmpCode: "CSLV011196", Name: "B Kashim Sab" },
  { Company: "TTPS", EmpCode: "CSLV007142", Name: "Shiv Shankar Gouda" },
  { Company: "TTPS", EmpCode: "CSLV007066", Name: "Kanchan Singh" },
  { Company: "TTPS", EmpCode: "CSLV109029", Name: "Sahil" },
  { Company: "TTPS", EmpCode: "CSLV009428", Name: "Kalappa G" },
  { Company: "TTPS", EmpCode: "CSLV007143", Name: "Hemant Sharma" },
  { Company: "TTPS", EmpCode: "CSLV007102", Name: "Eeresh" },
  { Company: "TTPS", EmpCode: "CSLV007071", Name: "Santosh Kumar Singh" },
  { Company: "TTPS", EmpCode: "CSLV079260", Name: "Chinnatti Narendra" },
  { Company: "TTPS", EmpCode: "CSLV014690", Name: "K Thippeswamy" },
  { Company: "TTPS", EmpCode: "CSLV011762", Name: "Ramanjani Kumar" },
  { Company: "TTPS", EmpCode: "CSLV011424", Name: "Veeranna Gouda" },
  { Company: "TTPS", EmpCode: "CSLV010857", Name: "Ashok G" },
  { Company: "TTPS", EmpCode: "CSLV009947", Name: "Somappa G" },
  { Company: "TTPS", EmpCode: "CSLV008951", Name: "Md Rafik" },
  { Company: "TTPS", EmpCode: "CSLV008480", Name: "A Shivraj" },
  { Company: "TTPS", EmpCode: "CSLV007445", Name: "Shivakumar H" },
  { Company: "TTPS", EmpCode: "CSLV004409", Name: "K. N Raghunath" },
  { Company: "TTPS", EmpCode: "CSLV000730", Name: "Hanumanthappa G.T" },
  { Company: "TTPS", EmpCode: "CSLV007084", Name: "D.Suresh" },
  { Company: "TTPS", EmpCode: "CSLV075070", Name: "Indrajit Mahanta" },
  { Company: "TTPS", EmpCode: "CSLV054546", Name: "Debadatta Swain" },
  { Company: "TTPS", EmpCode: "CSLV013063", Name: "Mahendra Kumar D" },
  { Company: "TTPS", EmpCode: "CSLV007081", Name: "Veeresh U" },
  { Company: "TTPS", EmpCode: "CSLV010270", Name: "Gajanand Patil" },
  { Company: "TTPS", EmpCode: "CSLV006942", Name: "Mallikarjun B" },
  { Company: "Bilwa", EmpCode: "CSLV017320", Name: "K Yeriswamy" },
  { Company: "Bilwa", EmpCode: "CSLV017317", Name: "D Rajanna" }
];
