export const data = [
  { Company: "JSW", EmpCode: "7045087", Name: "Rajesh K" },
  { Company: "JSW", EmpCode: "7042000", Name: "Shashidhar Patil" },
  { Company: "JSW", EmpCode: "1101744", Name: "Abhishek Marwadi" },
  { Company: "JSW", EmpCode: "7045723", Name: "Prashanth" },
  { Company: "JSW", EmpCode: "7045599", Name: "Ganga K T" },
  { Company: "JSW", EmpCode: "1049303", Name: "Indi Omkareshwar" },
  { Company: "JSW", EmpCode: "1046499", Name: "Panchadarla Srinu" },
  { Company: "JSW", EmpCode: "1046850", Name: "Vijay Durgesh K G" },
  { Company: "JSW", EmpCode: "1101421", Name: "Vighnesh Mhatre" },
  { Company: "JSW", EmpCode: "1098394", Name: "Ranganath" },
  { Company: "JSW", EmpCode: "1096588", Name: "Dinesh Panwar" },
  { Company: "JSW", EmpCode: "1089219", Name: "Abhimanyu Sharma" },
  { Company: "JSW", EmpCode: "1049295", Name: "Honnuraswamy K" },
  { Company: "JSW", EmpCode: "1023097", Name: "Swamy L M" },
  { Company: "JSW", EmpCode: "1022784", Name: "Karthik A R" },
  { Company: "JSW", EmpCode: "1018443", Name: "Subhansab Mattihalli" },
  { Company: "TTPS", EmpCode: "CSLV079826", Name: "Amrender Tiwari" },
  { Company: "TTPS", EmpCode: "CSLV007219", Name: "Mukesh Prajapati" },
  { Company: "TTPS", EmpCode: "CSLV099777", Name: "Parasurama HP" },
  { Company: "TTPS", EmpCode: "CSLV098624", Name: "Fayazahmad Nadaf" },
  { Company: "TTPS", EmpCode: "CSLV086507", Name: "Dangi Hemantharaj" },
  { Company: "TTPS", EmpCode: "CSLV076425", Name: "G M Thippeswamy" },
  { Company: "TTPS", EmpCode: "CSLV063576", Name: "P Rakesh Kumar" },
  { Company: "TTPS", EmpCode: "CSLV056474", Name: "Maruthi" },
  { Company: "TTPS", EmpCode: "CSLV016636", Name: "Manjunatha N" },
  { Company: "TTPS", EmpCode: "CSLV011196", Name: "B Kashim Sab" },
  { Company: "TTPS", EmpCode: "CSLV007142", Name: "Shiv Shankar Gouda" },
  { Company: "TTPS", EmpCode: "CSLV007066", Name: "Kanchan Singh" },
  { Company: "TTPS", EmpCode: "CSLV109029", Name: "Sahil" },
  { Company: "TTPS", EmpCode: "CSLV009428", Name: "Kalappa G" },
  { Company: "TTPS", EmpCode: "CSLV007143", Name: "Hemant Sharma" },
  { Company: "TTPS", EmpCode: "CSLV007102", Name: "Eeresh" },
  { Company: "TTPS", EmpCode: "CSLV007071", Name: "Santosh Kumar Singh" },
  { Company: "TTPS", EmpCode: "CSLV079260", Name: "Chinnatti Narendra" },
  { Company: "TTPS", EmpCode: "CSLV014690", Name: "K Thippeswamy" },
  { Company: "TTPS", EmpCode: "CSLV011762", Name: "Ramanjani Kumar" },
  { Company: "TTPS", EmpCode: "CSLV011424", Name: "Veeranna Gouda" },
  { Company: "TTPS", EmpCode: "CSLV010857", Name: "Ashok G" },
  { Company: "TTPS", EmpCode: "CSLV009947", Name: "Somappa G" },
  { Company: "TTPS", EmpCode: "CSLV008951", Name: "Md Rafik" },
  { Company: "TTPS", EmpCode: "CSLV008480", Name: "A Shivraj" },
  { Company: "TTPS", EmpCode: "CSLV007445", Name: "Shivakumar H" },
  { Company: "TTPS", EmpCode: "CSLV004409", Name: "K. N Raghunath" },
  { Company: "TTPS", EmpCode: "CSLV000730", Name: "Hanumanthappa G.T" },
  { Company: "TTPS", EmpCode: "CSLV007084", Name: "D.Suresh" },
  { Company: "TTPS", EmpCode: "CSLV075070", Name: "Indrajit Mahanta" },
  { Company: "TTPS", EmpCode: "CSLV054546", Name: "Debadatta Swain" },
  { Company: "TTPS", EmpCode: "CSLV013063", Name: "Mahendra Kumar D" },
  { Company: "TTPS", EmpCode: "CSLV007081", Name: "Veeresh U" },
  { Company: "TTPS", EmpCode: "CSLV010270", Name: "Gajanand Patil" },
  { Company: "TTPS", EmpCode: "CSLV006942", Name: "Mallikarjun B" },
  { Company: "Bilwa", EmpCode: "CSLV017320", Name: "K Yeriswamy" },
  { Company: "Bilwa", EmpCode: "CSLV017317", Name: "D Rajanna" }
];

export const desc = [
  " is specialized in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, ensuring expertise in emergency response and safety procedures.",
  " is proficient in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, enhancing workplace safety and risk management.",
  " has expertise in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, ensuring quick and effective emergency handling.",
  " is trained in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, improving emergency preparedness and fire safety.",
  " specializes in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation to enhance industrial safety standards.",
  " has advanced knowledge of First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, ensuring a proactive approach to workplace safety.",
  " is skilled in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, providing essential life-saving techniques and fire safety measures.",
  " has mastered First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, making them an asset in emergency situations.",
  " is well-trained in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, ensuring quick response and effective risk mitigation.",
  " is experienced in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, contributing to a safer and well-prepared workplace.",
  " excels in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, reinforcing industrial safety and compliance.",
  " has a strong background in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, ensuring effective emergency interventions.",
  " demonstrates expertise in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, providing critical safety solutions.",
  " is an expert in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, ensuring best practices in emergency scenarios.",
  " is highly skilled in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, strengthening workforce preparedness for critical incidents.",
  " has in-depth knowledge of First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, making them a key asset in workplace safety.",
  " is proficient in handling First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, ensuring efficiency in emergency management.",
  " has completed extensive training in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, making them a trusted safety expert.",
  " is a specialist in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, ensuring compliance with the highest safety standards.",
  " is well-versed in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, supporting effective risk assessment and mitigation.",
  " is highly specialized in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, ensuring top-notch safety standards in industrial settings.",
  " is well-equipped with skills in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, ensuring a proactive safety culture.",
  " has extensive experience in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, ensuring prompt and effective emergency responses.",
  " has undergone rigorous training in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, ensuring workplace safety excellence.",
  " is committed to safety excellence through expertise in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " is a safety professional trained in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, reducing risks effectively.",
  " is an expert in executing First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation for industrial safety compliance.",
  " has demonstrated excellence in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, contributing to a safer work environment.",
  " excels in emergency preparedness with skills in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " has deep expertise in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, ensuring operational safety across industries.",
  " is a trained specialist in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, enhancing workplace security.",
  " plays a key role in workplace safety with specialization in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " is well-trained in executing First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation to minimize emergency risks.",
  " brings expertise in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, ensuring a safer workforce environment.",
  " is a safety expert trained in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, maintaining high safety standards.",
  " demonstrates efficiency in handling First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation in emergency situations.",
  " ensures safety compliance through specialization in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " contributes to a secure workplace with knowledge of First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " is an emergency response specialist with expertise in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " is well-versed in fire safety and emergency procedures, including First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " ensures rapid emergency handling through proficiency in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " has acquired hands-on expertise in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, ensuring safety readiness.",
  " plays a critical role in emergency management by excelling in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " is committed to industrial safety and trained in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " upholds workplace safety by mastering First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " enhances workplace safety measures through specialization in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " provides expert-level safety solutions through knowledge of First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " ensures quick emergency response through mastery of First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " contributes to industrial hazard prevention through skills in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " actively supports safety initiatives with expertise in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " is an emergency response expert specializing in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " strengthens workplace risk management through training in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " ensures safety protocol adherence with in-depth knowledge of First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " applies best practices in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation to prevent workplace hazards.",
  " enhances industrial safety culture through training in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " is a certified safety expert in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation, reducing workplace risks.",
  " strengthens safety measures with expert training in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " supports emergency action planning through knowledge of First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " is dedicated to workplace safety with expertise in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation.",
  " ensures workplace resilience by specializing in First Aid, Hose Connection, Hose Drill, BA Set Use, Forearm Rescue Method, and Extinguisher Operation."
];
